language: python

python:
- '3.6'
- '3.7'

# Run command before install
install:
- pip install sympy strictyaml networkx

# Run command for testing
script:
- python setup.py develop
- pytest

deploy:
  provider: pypi
  user: __token__
  password:
    secure: "AmJDjp/PvhU3+NF7kEAxFrbTTG8/5UYJAOhqtO1BEq8SJH1mQ40EbNJWCuPhzNrAGGNrM42t4gcVxj5xW1PxedAh4f5+xslXYil+mCvoDv2HtyLG0G4woNUAFW3BbG0gwEDq7+pEq/ZVdnojDI4Uka+lTEb+FHX5KF8nxkYae0FXUjriATI/CiuAk7vmbhtEFyJh3fv/9yYxH5rWGRdBbKvVBRlEA1G5Hso45ANZ71sLUEYmrAtyLvSaBH5+asoJNjjvZZdQhvX+YKR5GtH+uDeC28O4P+LYBfdA1NAQlg6Rp6PQuG2nEPTPQbVBBdMkZJcSfq2jL5mGYeT42MokX+F9+eFT9lJoqtj/qWCzswREZagYNacuGTSBxl75TcRiCV/ivYxKd3Fu2JuCcQaDo5Hjz/16yaXP+Mg0sB/ROnpU55tqzUumvjHyry5mdWWbngXx5R7NOeA4KGyFaNhjnB1RlU1btiEPg4+0E/J34ww9boCOjpjTCWwNK+b3OCuisg1AYrAeDoOc2ynF7JV3Uwg71m0sWgYNjz4CUjD7B7cF9C03dV645pf8r2pKOvBlNrGEe7x/JJFD44EIXEuYbi8XBZ7rJoycgkDPZq+plYcbZdAGDHOd7TyhQiyjARpf0w5xEMIhgVGbsoGeH5JlUi2gXi3sWvNT0JUzp8ANgWw="
  on:
    tags: true
